### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by ThreaT** [FarmBot/docs#1]
I would like to get involved and contribute but there are so many repositories and I'm not really sure how they all fit together. It would be really useful to have an overview on what's doing what and how they relate to each other if possible!

**Comment by ThreaT** [comment]
Nevermind, [found it](http://farmbot.cc/wiki/Contributors_Guide)!

**Comment by RickCarlino** [comment]
Hey @ThreaT , thanks for letting us know. One great way to help is by pointing out documentation issues (which are not easy for us to find), so I really appreciate it.

You can come visit us in the [chat room](https://gitter.im/FarmBot/chat) if you want to say 'hi' or have any specific questions.
